/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FoodDelivery.gui.user;

import FoodDelivery.dao.CourierDAO;
import FoodDelivery.dao.OrderDAO;
import FoodDelivery.gui.styling.Home;
import FoodDelivery.models.Courier;
import java.util.Map;

/**
 *
 * @author Kenzie Taqiyassar
 */
public class DeliveryPage extends javax.swing.JFrame {

    private int userId;
    private int courierId;
    private int orderId;
    private int restaurantId;
    private int paymentId;

    public DeliveryPage() {
        initComponents();
    }

    public DeliveryPage(Map<String, Integer> generatedIds) {
        initComponents();
        this.courierId = generatedIds.get("courierId");
        this.userId = generatedIds.get("userId");
        this.orderId = generatedIds.get("orderId");
        this.restaurantId = generatedIds.get("restaurantId");
        this.paymentId = generatedIds.get("paymentId");
        finishedPanel.setVisible(false);

        CourierDAO courierDAO = new CourierDAO();
        Courier courier = courierDAO.getCourierByOrderID(orderId);
        courierName.setText("Name: " + courier.getName());
        courierPhone.setText("Phone Number: " + courier.getPhoneNumber());
        courierPlate.setText("Plate Number: " + courier.getPlateNumber());
    }

    public DeliveryPage(int restoId, int userId, int paymentId, int orderId, int courierId) {
        initComponents();
        this.courierId = courierId;
        this.userId = userId;
        this.orderId = orderId;
        finishedPanel.setVisible(false);

        CourierDAO courierDAO = new CourierDAO();
        Courier courier = courierDAO.getCourierByOrderID(orderId);
        courierName.setText("Name: " + courier.getName());
        courierPhone.setText("Phone Number: " + courier.getPhoneNumber());
        courierPlate.setText("Plate Number: " + courier.getPlateNumber());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        containerPanel = new javax.swing.JPanel();
        deliveryPanel = new javax.swing.JPanel();
        courierName = new javax.swing.JLabel();
        courierPhone = new javax.swing.JLabel();
        confirmOrderButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        courierPlate = new javax.swing.JLabel();
        finishedPanel = new javax.swing.JPanel();
        thanksLabel = new javax.swing.JLabel();
        backToHomeButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1440, 800));

        containerPanel.setBackground(new java.awt.Color(255, 255, 255));
        containerPanel.setLayout(new java.awt.CardLayout());

        deliveryPanel.setBackground(new java.awt.Color(255, 255, 255));

        courierName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        courierName.setText("Name: ");

        courierPhone.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        courierPhone.setText("Phone Number:");

        confirmOrderButton.setBackground(new java.awt.Color(1, 127, 245));
        confirmOrderButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        confirmOrderButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmOrderButton.setText("Confirm Order has been received");
        confirmOrderButton.setMaximumSize(new java.awt.Dimension(75, 25));
        confirmOrderButton.setMinimumSize(new java.awt.Dimension(75, 25));
        confirmOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmOrderButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel6.setText("Your order is being delivered by:");

        courierPlate.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        courierPlate.setText("Plate Number:");

        javax.swing.GroupLayout deliveryPanelLayout = new javax.swing.GroupLayout(deliveryPanel);
        deliveryPanel.setLayout(deliveryPanelLayout);
        deliveryPanelLayout.setHorizontalGroup(
            deliveryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deliveryPanelLayout.createSequentialGroup()
                .addGroup(deliveryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deliveryPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(deliveryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(courierPhone)
                            .addComponent(courierPlate)
                            .addComponent(courierName, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(deliveryPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(deliveryPanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(confirmOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        deliveryPanelLayout.setVerticalGroup(
            deliveryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deliveryPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(courierName)
                .addGap(18, 18, 18)
                .addComponent(courierPhone)
                .addGap(18, 18, 18)
                .addComponent(courierPlate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE)
                .addComponent(confirmOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        containerPanel.add(deliveryPanel, "card2");

        finishedPanel.setBackground(new java.awt.Color(255, 255, 255));

        thanksLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        thanksLabel.setText("Thanks for the Order!");

        backToHomeButton.setBackground(new java.awt.Color(1, 127, 245));
        backToHomeButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        backToHomeButton.setForeground(new java.awt.Color(255, 255, 255));
        backToHomeButton.setText("Back to HomePage");
        backToHomeButton.setMaximumSize(new java.awt.Dimension(75, 25));
        backToHomeButton.setMinimumSize(new java.awt.Dimension(75, 25));
        backToHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToHomeButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel4.setText("Order Finished");

        javax.swing.GroupLayout finishedPanelLayout = new javax.swing.GroupLayout(finishedPanel);
        finishedPanel.setLayout(finishedPanelLayout);
        finishedPanelLayout.setHorizontalGroup(
            finishedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(finishedPanelLayout.createSequentialGroup()
                .addGroup(finishedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(finishedPanelLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel4))
                    .addGroup(finishedPanelLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(thanksLabel))
                    .addGroup(finishedPanelLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(backToHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        finishedPanelLayout.setVerticalGroup(
            finishedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(finishedPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(thanksLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backToHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        containerPanel.add(finishedPanel, "card2");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(containerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(767, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(containerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToHomeButtonActionPerformed
        Home home = new Home(this.userId);
        this.dispose();
        home.setVisible(true);
    }//GEN-LAST:event_backToHomeButtonActionPerformed

    private void confirmOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmOrderButtonActionPerformed
        deliveryPanel.setVisible(false);
        finishedPanel.setVisible(true);
        CourierDAO courier = new CourierDAO();
        courier.updateCourierStatusDelivered(this.orderId);
        OrderDAO order = new OrderDAO();
        order.setOrderStatusFinished(this.orderId);

    }//GEN-LAST:event_confirmOrderButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliveryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliveryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliveryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliveryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliveryPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToHomeButton;
    private javax.swing.JButton confirmOrderButton;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JLabel courierName;
    private javax.swing.JLabel courierPhone;
    private javax.swing.JLabel courierPlate;
    private javax.swing.JPanel deliveryPanel;
    private javax.swing.JPanel finishedPanel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel thanksLabel;
    // End of variables declaration//GEN-END:variables
}
