/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FoodDelivery.gui.styling.components;

import FoodDelivery.dao.ReceiptDAO;
import java.util.List;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kenzie Taqiyassar
 */
public class ReceiptCard extends javax.swing.JPanel {

    /**
     * Creates new form ReceiptCard
     */
    private int userId;
    private List<Map<String, Object>> receiptDataList;

    public ReceiptCard(int userId) {
        initComponents();
        this.userId = userId;
        this.receiptDataList = receiptDataList;
        initialize(); // You can create a separate method for initialization
        ReceiptDAO receipt = new ReceiptDAO();
        List<Map<String, Object>> receiptDataList = receipt.getReceiptDataListForUserId(userId);
        if (!receiptDataList.isEmpty()) {
            for (Map<String, Object> receiptData : receiptDataList) {
                courierNameReceipt.setText("Name: " + receiptData.get("courierName"));
                courierPlateNumber.setText("Plate Number: " + receiptData.get("courierPlateNumber"));
                userName.setText("username: " + receiptData.get("userName"));
                userPhone.setText("user phone: " + receiptData.get("userPhoneNumber"));
                userAddress.setText("address: " + receiptData.get("userAddress"));
                orderDate.setText("Order-date: " + receiptData.get("orderDate"));
                restaurantName.setText("restaurant name: " + receiptData.get("restaurantName"));
                DefaultTableModel model = new DefaultTableModel();
                model.setColumnIdentifiers(new Object[]{"Product Name", "Quantity", "Subtotal"});
                List<Map<String, Object>> itemList = (List<Map<String, Object>>) receiptData.get("items");
                for (Map<String, Object> item : itemList) {
                    model.addRow(new Object[]{item.get("product_name"), item.get("quantity"), item.get("subtotal")});
                }
                orderDetailTable.setModel(model);
                shippingCost.setText("Shipping cost: " + receiptData.get("shippingCost"));
                orderTotal.setText("Order total: " + receiptData.get("orderTotal"));
                orderIdReceipt.setText("Order ID: " + receiptData.get("orderId"));
                paymentMethod.setText("Payment method: " + receiptData.get("paymentMethod"));
            }
        }

    }

    public void initialize() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        receiptPanel = new javax.swing.JPanel();
        courierNameReceipt = new javax.swing.JLabel();
        courierPlateNumber = new javax.swing.JLabel();
        restaurantName = new javax.swing.JLabel();
        orderTotal = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        userPhone = new javax.swing.JLabel();
        userAddress = new javax.swing.JLabel();
        orderDate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        shippingCost = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderDetailTable = new javax.swing.JTable();
        orderIdReceipt = new javax.swing.JLabel();
        paymentMethod = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        receiptPanel.setBackground(new java.awt.Color(255, 255, 255));
        receiptPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        courierNameReceipt.setText("courierName:");

        courierPlateNumber.setText("courier Plate Number:");

        restaurantName.setText("restaurant name:");

        orderTotal.setText("Order total:");

        userName.setText("username:");

        userPhone.setText("user phone:");

        userAddress.setText("address");

        orderDate.setText("Order Date:");

        shippingCost.setText("Shipping cost:");

        orderDetailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "quantity", "name", "subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orderDetailTable);

        orderIdReceipt.setText("Order Id:");

        paymentMethod.setText("Payment Method:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel7.setText("Receipt");

        javax.swing.GroupLayout receiptPanelLayout = new javax.swing.GroupLayout(receiptPanel);
        receiptPanel.setLayout(receiptPanelLayout);
        receiptPanelLayout.setHorizontalGroup(
            receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receiptPanelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(receiptPanelLayout.createSequentialGroup()
                        .addComponent(userAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(41, 41, 41))
                    .addGroup(receiptPanelLayout.createSequentialGroup()
                        .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(courierNameReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(courierPlateNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(userPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(restaurantName, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orderDate, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(receiptPanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(shippingCost, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(receiptPanelLayout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(orderTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(orderIdReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(paymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 11, Short.MAX_VALUE))))
        );
        receiptPanelLayout.setVerticalGroup(
            receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receiptPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userPhone)
                .addGap(18, 18, 18)
                .addComponent(userAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(courierNameReceipt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(courierPlateNumber)
                .addGap(26, 26, 26)
                .addComponent(orderDate)
                .addGap(18, 18, 18)
                .addComponent(restaurantName)
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(receiptPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1))
                    .addGroup(receiptPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(shippingCost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(orderTotal)
                .addGap(18, 18, 18)
                .addComponent(orderIdReceipt)
                .addGap(18, 18, 18)
                .addComponent(paymentMethod)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(receiptPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(receiptPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel courierNameReceipt;
    private javax.swing.JLabel courierPlateNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel orderDate;
    private javax.swing.JTable orderDetailTable;
    private javax.swing.JLabel orderIdReceipt;
    private javax.swing.JLabel orderTotal;
    private javax.swing.JLabel paymentMethod;
    private javax.swing.JPanel receiptPanel;
    private javax.swing.JLabel restaurantName;
    private javax.swing.JLabel shippingCost;
    private javax.swing.JLabel userAddress;
    private javax.swing.JLabel userName;
    private javax.swing.JLabel userPhone;
    // End of variables declaration//GEN-END:variables
}
