/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package basdat8.gui;

import basdat8.dao.McdonaldDAO;
import basdat8.models.Mcdonald;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class McdonaldPanel extends javax.swing.JFrame {

    private DefaultTableModel model;

    /**
     * Creates new form McdonaldPanel
     */
    public McdonaldPanel() {
        initComponents();
        McdonaldDAO mcdonaldDAO = new McdonaldDAO();
        
        model = (DefaultTableModel) DataTableMcDonald.getModel();
        insertDataIntoTable(mcdonaldDAO.getAllMcdonald());
    }

        
    private void insertDataIntoTable(List<Mcdonald> mcDonaldList) {
        // Clear existing data
        model.setRowCount(0);

        // Iterate through the data and add it to the JTable
        for (Mcdonald mekdi : mcDonaldList) {
            Object[] row = {mekdi.getIdMcdonald(), mekdi.getNamaCabang()};
            model.addRow(row);
            System.out.println(mekdi.getIdMcdonald() + mekdi.getNamaCabang());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        DataTableMcDonald = new javax.swing.JTable();
        backToAdminHome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtIdMcd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNamaCabang = new javax.swing.JTextField();
        buttonSubmitMenu = new javax.swing.JButton();
        buttonEditMenu = new javax.swing.JButton();
        buttonDeleteMenu = new javax.swing.JButton();
        buttonClearMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DataTableMcDonald.setAutoCreateRowSorter(true);
        DataTableMcDonald.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idMcd", "NamaCabang"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DataTableMcDonald.setShowGrid(true);
        DataTableMcDonald.getTableHeader().setReorderingAllowed(false);
        DataTableMcDonald.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DataTableMcDonaldMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DataTableMcDonald);
        if (DataTableMcDonald.getColumnModel().getColumnCount() > 0) {
            DataTableMcDonald.getColumnModel().getColumn(0).setResizable(false);
            DataTableMcDonald.getColumnModel().getColumn(1).setResizable(false);
        }

        backToAdminHome.setText("< Back");
        backToAdminHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToAdminHomeActionPerformed(evt);
            }
        });

        jLabel1.setText("idMcd");

        txtIdMcd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIdMcdMouseClicked(evt);
            }
        });
        txtIdMcd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdMcdActionPerformed(evt);
            }
        });

        jLabel2.setText("NamaCabang");

        txtNamaCabang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaCabangActionPerformed(evt);
            }
        });

        buttonSubmitMenu.setText("Create");
        buttonSubmitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitMenuActionPerformed(evt);
            }
        });

        buttonEditMenu.setText("Save Changes");
        buttonEditMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditMenuActionPerformed(evt);
            }
        });

        buttonDeleteMenu.setText("Delete");
        buttonDeleteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteMenuActionPerformed(evt);
            }
        });

        buttonClearMenu.setText("Clear");
        buttonClearMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(backToAdminHome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonSubmitMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonEditMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonDeleteMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonClearMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtIdMcd, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamaCabang, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backToAdminHome)
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdMcd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNamaCabang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonSubmitMenu)
                            .addComponent(buttonEditMenu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonDeleteMenu)
                            .addComponent(buttonClearMenu)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToAdminHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToAdminHomeActionPerformed
        // TODO add your handling code here:
        AdminPanel adminPanel = new AdminPanel();
        adminPanel.setVisible(true);
        dispose();
    }//GEN-LAST:event_backToAdminHomeActionPerformed

    private void txtIdMcdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdMcdMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMcdMouseClicked

    private void txtIdMcdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMcdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMcdActionPerformed

    private void txtNamaCabangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaCabangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaCabangActionPerformed

    private void buttonSubmitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSubmitMenuActionPerformed

    private void buttonEditMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEditMenuActionPerformed

    private void buttonDeleteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDeleteMenuActionPerformed

    private void buttonClearMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearMenuActionPerformed
        // TODO add your handling code here:
        txtIdMcd.setText(null);
        txtNamaCabang.setText(null);
    }//GEN-LAST:event_buttonClearMenuActionPerformed

    private void DataTableMcDonaldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataTableMcDonaldMouseClicked
        // TODO add your handling code here:
        txtIdMcd.setEnabled(false);
        model = (DefaultTableModel) DataTableMcDonald.getModel();
        int selectedIndex = DataTableMcDonald.getSelectedRow();
        
        txtIdMcd.setText(model.getValueAt(selectedIndex, 0).toString());
        txtNamaCabang.setText(model.getValueAt(selectedIndex, 1).toString());
    }//GEN-LAST:event_DataTableMcDonaldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(McdonaldPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(McdonaldPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(McdonaldPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(McdonaldPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new McdonaldPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DataTableMcDonald;
    private javax.swing.JButton backToAdminHome;
    private javax.swing.JButton buttonClearMenu;
    private javax.swing.JButton buttonDeleteMenu;
    private javax.swing.JButton buttonEditMenu;
    private javax.swing.JButton buttonSubmitMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtIdMcd;
    private javax.swing.JTextField txtNamaCabang;
    // End of variables declaration//GEN-END:variables
}
