/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FoodDelivery.gui.login;

import FoodDelivery.gui.styling.*;

import javax.swing.ImageIcon;

import FoodDelivery.dao.RestaurantDAO;
import FoodDelivery.gui.restaurant.RestaurantDashboardPage;

/**
 *
 * @author Naufal Romero
 */
public class LoginChooser extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public LoginChooser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        customerLabel = new javax.swing.JLabel();
        restaurantLabel = new javax.swing.JLabel();
        loginTitleLable = new javax.swing.JLabel();
        customerIcon = new javax.swing.JLabel();
        customerIcon2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        restauranticon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(464, 521));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        customerLabel.setBackground(new java.awt.Color(255, 255, 255));
        customerLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        customerLabel.setForeground(new java.awt.Color(51, 102, 255));
        customerLabel.setText("Customer");
        customerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerLabelMouseClicked(evt);
            }
        });
        customerLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                customerLabelKeyPressed(evt);
            }
        });

        restaurantLabel.setBackground(new java.awt.Color(255, 255, 255));
        restaurantLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        restaurantLabel.setForeground(new java.awt.Color(51, 102, 255));
        restaurantLabel.setText("Restaurant");

        loginTitleLable.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        loginTitleLable.setText("Login");

        customerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FoodDelivery/assets/customerMale-icon.png"))); // NOI18N
        customerIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerIconMouseClicked(evt);
            }
        });
        customerIcon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                customerIconKeyPressed(evt);
            }
        });

        customerIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FoodDelivery/assets/customerFemale-icon.png"))); // NOI18N
        customerIcon2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerIcon2MouseClicked(evt);
            }
        });

        jLabel7.setText("or");

        restauranticon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FoodDelivery/assets/restaurant-icon.png"))); // NOI18N
        restauranticon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restauranticonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(customerIcon)
                        .addGap(62, 62, 62)
                        .addComponent(customerIcon2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(loginTitleLable))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerLabel)
                            .addComponent(restauranticon)
                            .addComponent(restaurantLabel))))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(loginTitleLable, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customerIcon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addComponent(customerLabel)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(28, 28, 28)
                .addComponent(restauranticon)
                .addGap(18, 18, 18)
                .addComponent(restaurantLabel)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void customerLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerLabelMouseClicked
        // TODO add your handling code here:
        LoginCustomer cust = new LoginCustomer();
        this.dispose();
        cust.setVisible(true);

    }//GEN-LAST:event_customerLabelMouseClicked

    private void customerLabelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerLabelKeyPressed
        // TODO add your handling code here:
        LoginCustomer cust = new LoginCustomer();
        this.dispose();
        cust.setVisible(true);
    }//GEN-LAST:event_customerLabelKeyPressed

    private void customerIconKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerIconKeyPressed
        // TODO add your handling code here:
        LoginCustomer cust = new LoginCustomer();
        this.dispose();
        cust.setVisible(true);
    }//GEN-LAST:event_customerIconKeyPressed

    private void customerIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerIconMouseClicked
        // TODO add your handling code here:
        LoginCustomer cust = new LoginCustomer();
        this.dispose();
        cust.setVisible(true);
    }//GEN-LAST:event_customerIconMouseClicked

    private void customerIcon2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerIcon2MouseClicked
        // TODO add your handling code here:
        LoginCustomer cust = new LoginCustomer();
        this.dispose();
        cust.setVisible(true);
    }//GEN-LAST:event_customerIcon2MouseClicked

    private void restauranticonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restauranticonMouseClicked
        // TODO add your handling code here:
        LoginRestaurant resto = new LoginRestaurant();
        this.dispose();
        resto.setVisible(true);
    }//GEN-LAST:event_restauranticonMouseClicked

    private void emailFieldLoginRestaurantActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_emailFieldLoginRestaurantActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_emailFieldLoginRestaurantActionPerformed

    private void passwordFieldLoginRestaurantActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_passwordFieldLoginRestaurantActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_passwordFieldLoginRestaurantActionPerformed

    private void buttonToSignUpPageActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonToSignUpPageActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }// GEN-LAST:event_buttonToSignUpPageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginChooser.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginChooser.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginChooser.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginChooser.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginChooser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel customerIcon;
    private javax.swing.JLabel customerIcon2;
    private javax.swing.JLabel customerLabel;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel loginTitleLable;
    private javax.swing.JLabel restaurantLabel;
    private javax.swing.JLabel restauranticon;
    // End of variables declaration//GEN-END:variables
}
